/**
 * 2026-06-01
 * @author abdelhafid
 * @exports PATHS
 * @description single source of truth for routes
 */
export const PATHS = {
  HOME: '/',
  ALGEMEEN: '/algemene-voorwaarden',
  CONTACT: '/contact',
  DIENSTEN: '/diensten',
  OFFERTE: '/offerte',
  OVER_ONS: '/over-ons',
  OVERIG: '/overig',

  OVERIG_VLOERVERWARMING: '/overig/vloerverwarming',
  OVERIG_EGALISEREN: '/overig/egaliseren',
  OVERIG_GIETVLOEREN: '/overig/gietvloeren',
  OVERIG_TEGELEN: '/overig/tegelen',
  OVERIG_VLOER_VERWIJDEREN: '/overig/vloer-verwijderen',
  OVERIG_NATUURSTEEN: '/overig/natuursteen-behandelen',
  OVERIG_OPSLAG: '/overig/opslag',

  STOFFEREN_TRAP: '/stofferen/trap',
  STOFFEREN_VLOER: '/stofferen/vloer',
  STOFFEREN_TAPIJTTEGELS: '/stofferen/tapijttegels',
  STOFFEREN_MEUBELS: '/stofferen/meubels',
  STOFFEREN_DEURMAT: '/stofferen/deurmat',
  STOFFEREN_DROOGLOOPMAT: '/stofferen/droogloopmat',
  STOFFEREN_RODE_LOPER: '/stofferen/rode-loper',
  STOFFEREN_REINIGING: '/stofferen/reinigingsservice',
  STOFFEREN_TAPIJT_VERWIJDEREN: '/stofferen/tapijt-verwijderen',

  PARKET_SCHUREN_POLIJSTEN: '/parketrenovatie/schuren-en-polijsten',
  PARKET_SCHUREN_LAKKEN: '/parketrenovatie/schuren-en-lakken',
  PARKET_SCHUREN_OLIEN: '/parketrenovatie/schuren-en-olien',
  PARKET_SCHUREN_HARDWAX: '/parketrenovatie/schuren-en-hardwaxen',
  PARKET_AANHELEN: '/parketrenovatie/aanhelen-uitbreiden',
  PARKET_REPARATIE: '/parketrenovatie/reparatie',
  PARKET_DREVELEN: '/parketrenovatie/drevelen',
  PARKET_V_GROEF: '/parketrenovatie/v-groef-frezen',
  PARKET_PLINTEN: '/parketrenovatie/plinten-en-deklijsten',
  PARKET_ROOT: '/parketrenovatie',

  VLOEREN_PARKET: '/vloeren-leggen/parket',
  VLOEREN_LAMINAAT: '/vloeren-leggen/laminaat',
  VLOEREN_PVC: '/vloeren-leggen/pvc',
  VLOEREN_TAPIJT: '/vloeren-leggen/tapijt',
  VLOEREN_LINOLEUM: '/vloeren-leggen/linoleum',
  VLOEREN_VINYL: '/vloeren-leggen/vinyl',
  VLOEREN_VISGRAAT: '/vloeren-leggen/visgraat',
  VLOEREN_WALVISGRAAT: '/vloeren-leggen/walvisgraat',
  VLOEREN_HONGAARSE_PUNT: '/vloeren-leggen/hongaarse-punt',
  VLOEREN_WEENSE_PUNT: '/vloeren-leggen/weense-punt',
  VLOEREN_PVC_TEGELS: '/vloeren-leggen/pvc-tegels',
  VLOEREN_MOZAIEK: '/vloeren-leggen/mozaiek-of-patroon',
  VLOEREN_HEXAGON: '/vloeren-leggen/hexagon-&-3d',
  VLOEREN_TAPIS: '/vloeren-leggen/tapis',
  VLOEREN_BOURGOGNE: '/vloeren-leggen/bourgogne',
  VLOEREN_ROOT: '/vloeren-leggen',

  TRAP_PVC: '/traprenovatie/bekleden-met-pvc',
  TRAP_LAMINAAT: '/traprenovatie/bekleden-met-laminaat',
  TRAP_HOUT: '/traprenovatie/bekleden-met-hout',
  TRAP_TAPIJT: '/traprenovatie/bekleden-met-tapijt',
  TRAP_LINOLEUM: '/traprenovatie/bekleden-met-linoleum',
  TRAP_SCHUREN_BEHANDELEN: '/traprenovatie/schuren-en-behandelen',
  TRAP_SCHUREN_SCHILDEREN: '/traprenovatie/schuren-en-schilderen',
  TRAP_BETON_METAL: '/traprenovatie/beton-cire/metal-stuc',
  TRAP_BETON_GLAMOUR: '/traprenovatie/beton-cire/glamour-stuc',
  TRAP_BETON_BRUT: '/traprenovatie/beton-cire/brut',
  TRAP_BETON_PAREL: '/traprenovatie/beton-cire/parel',
  TRAP_BETON_CROCO: '/traprenovatie/beton-cire/croco',
  TRAP_BETON_VENETIAANS: '/traprenovatie/beton-cire/venetiaans',
  TRAP_BETON_ACOUSTIC: '/traprenovatie/beton-cire/acoustic',
  TRAP_OPEN: '/traprenovatie/open-trap',
  TRAP_DICHT: '/traprenovatie/dichte-trap',
  TRAP_VERLICHTING: '/traprenovatie/verlichting',
  TRAP_ROOT: '/traprenovatie',

  TRAP_TAPIJT_STANDAARD: '/traprenovatie/standaard-tapijt',
  TRAP_TAPIJT_LOPER: '/traprenovatie/traploper',
  TRAP_TAPIJT_SISAL: '/traprenovatie/sisal-&-boucle',
  TRAP_TAPIJT_PATROON: '/traprenovatie/tapijt-met-patroon',
  TRAP_TAPIJT_VISGRAAT: '/traprenovatie/visgraat-tapijt',

  FAQ: '/veelgestelde-vragen',
  TEGELEN_ROOT: '/tegelen',
  VLOERVERWARMING_ROOT: '/vloerverwarming',
} as const;
