export interface LinkInfo {
  name: string;
  path: string;
}

export interface FooterColumnInfo {
  title: string;
  path: string;
  links: LinkInfo[];
}

export const topFooterLinks: LinkInfo[] = [
  { name: 'Home', path: '/' },
  { name: 'Over ons', path: '/over-ons' },
  { name: 'Diensten', path: '/diensten' },
  { name: 'Zakelijk', path: '/' },
  { name: 'Veelgestelde vragen', path: '/' },
  { name: 'Contact', path: '/' },
];
export const footerColumnsInfo: FooterColumnInfo[] = [
  {
    title: 'Traprenovatie',
    path: '/traprenovatie',
    links: [
      { name: 'Bekleden met PVC', path: '/traprenovatie/bekleden-met-pvc' },
      { name: 'Bekleden met laminaat', path: '/traprenovatie/bekleden-met-laminaat' },
      { name: 'Bekleden met hout', path: '/traprenovatie/bekleden-met-hout' },
      { name: 'Bekleden met tapijt', path: '/traprenovatie/bekleden-met-tapijt' },
      { name: 'Bekleden met linoleum', path: '/traprenovatie/bekleden-met-linoleum' },
      { name: 'Schuren en behandelen', path: '/traprenovatie/schuren-en-behandelen' },
      { name: 'Schuren en schilderen', path: '/traprenovatie/schuren-en-schilderen' },
      { name: 'Hout look', path: '/traprenovatie/hout-look' },
      { name: 'Beton look', path: '/traprenovatie/beton-look' },
      { name: 'Marmer look', path: '/traprenovatie/marmer-look' },
      { name: 'Cement look', path: '/traprenovatie/cement-look' },
      { name: 'Staal look', path: '/traprenovatie/staal-look' },
      { name: 'Beton Ciré Metal stuc', path: '/traprenovatie/betoncire-metal-stuc' },
      { name: 'Beton Ciré Glamour stuc', path: '/traprenovatie/betoncire-glamour-stuc' },
      { name: 'Beton Ciré Brut', path: '/traprenovatie/betoncire-brut' },
      { name: 'Beton Ciré Parel', path: '/traprenovatie/betoncire-parel' },
      { name: 'Beton Ciré Croco', path: '/traprenovatie/betoncire-croco' },
      { name: 'Beton Ciré Venetiaans', path: '/traprenovatie/betoncire-venetiaans' },
      { name: 'Beton Ciré Acoustic', path: '/traprenovatie/betoncire-acoustic' },
      { name: '', path: '' },
      { name: 'Open trap', path: '/traprenovatie/open-trap' },
      { name: 'Dichte trap', path: '/traprenovatie/dichte-trap' },
      { name: 'Verlichting', path: '/traprenovatie/verlichting' },
      { name: 'Tapijt verwijderen', path: '/traprenovatie/tapijt-verwijderen' },
    ],
  },
  {
    title: 'Tegelen',
    path: '/tegelen',
    links: [
      { name: 'Vloer', path: '/tegelen/vloer' },
      { name: 'Wand', path: '/tegelen/wand' },
      { name: 'Badkamer', path: '/tegelen/badkamer' },
      { name: 'Betonlook', path: '/tegelen/betonlook' },
      { name: 'Houtlook', path: '/tegelen/houtlook' },
      { name: 'Visgraat', path: '/tegelen/visgraat' },
      { name: 'Portugees', path: '/tegelen/portugees' },
      { name: 'Marokkaans', path: '/tegelen/marokkaans' },
      { name: 'Marmer', path: '/tegelen/marmer' },
      { name: 'Keramisch', path: '/tegelen/keramisch' },
      { name: 'Hexagon', path: '/tegelen/hexagon' },
    ],
  },
  {
    path: '/vloeren-leggen',
    title: 'Vloeren leggen',
    links: [
      { name: 'Parket ', path: '/vloeren-leggen/parket' },
      { name: 'Laminaat ', path: '/vloeren-leggen/laminaat' },
      { name: 'PVC ', path: '/vloeren-leggen/pvc' },
      { name: 'Tapijt ', path: '/vloeren-leggen/tapijt' },
      { name: 'Linoleum ', path: '/vloeren-leggen/linoleum' },
      { name: 'Visgraat', path: '/vloeren-leggen/visgraat' },
      { name: 'Walvisgraat', path: '/vloeren-leggen/walvisgraat' },
      { name: 'Hongaarse punt', path: '/vloeren-leggen/hongaarse-punt' },
      { name: 'Weense punt', path: '/vloeren-leggen/weense-punt' },
      { name: 'Tegel', path: '/vloeren-leggen/tegel' },
      { name: 'Mozaïek of patroon', path: '/vloeren-leggen/mozaiek-of-patroon' },
      { name: 'Hexagon & 3D', path: '/vloeren-leggen/hexagon-&-3d' },
      { name: 'Tapis', path: '/vloeren-leggen/tapis' },
      { name: 'Bourgogne', path: '/vloeren-leggen/bourgogne' },
    ],
  },
  {
    path: '/vloer-verwijderen',
    title: 'Vloer verwijderen',
    links: [
      { name: 'Parket', path: '/vloer-verwijderen/parket' },
      { name: 'PVC', path: '/vloer-verwijderen/pvc' },
      { name: 'Hout', path: '/vloer-verwijderen/hout' },
      { name: 'Linoleum', path: '/vloer-verwijderen/linoleum' },
      { name: 'Kurk', path: '/vloer-verwijderen/kurk' },
      { name: 'Tegels', path: '/vloer-verwijderen/tegels' },
      { name: 'Marmer', path: '/vloer-verwijderen/marmer' },
      { name: 'Graniet', path: '/vloer-verwijderen/graniet' },
      { name: 'Lijmesten', path: '/vloer-verwijderen/lijmesten' },
      { name: 'Vinyl', path: '/vloer-verwijderen/vinyl' },
      { name: 'Zandcement dekvloer', path: '/vloer-verwijderen/zandcement-dekvloer' },
    ],
  },
  {
    path: '/gietvloeren',
    title: 'Gietvloeren',
    links: [
      { name: 'Epoxy', path: '/gietvloeren/epoxy' },
      { name: 'PU', path: '/gietvloeren/pu' },
      { name: 'Woonbeton', path: '/gietvloeren/woonbeton' },
      { name: 'Beton', path: '/gietvloeren/beton' },
      { name: 'Beton Ciré', path: '/gietvloeren/betoncire' },
    ],
  },
  {
    title: 'Parket renovatie',
    path: '/parketrenovatie',
    links: [
      { name: 'Schuren en polijsten', path: '/parketrenovatie/schuren-en-polijsten' },
      { name: 'Schuren en lakken', path: '/parketrenovatie/schuren-en-lakken' },
      { name: 'Schuren en oliën', path: '/parketrenovatie/schuren-en-olien' },
      { name: 'Schuren en hardwaxen', path: '/parketrenovatie/schuren-en-hardwaxen' },
      { name: 'Aanhelen / Uitbreiden', path: '/parketrenovatie/aanhelen-uitbreiden' },
      { name: 'Reparatie', path: '/parketrenovatie/reparatie' },
      { name: 'Drevelen', path: '/parketrenovatie/drevelen' },
      { name: 'V-groef frezen', path: '/parketrenovatie/v-groef-frezen' },
      { name: 'Plinten & Deklijsten', path: '/parketrenovatie/plinten-en-deklijsten' },
    ],
  },
  {
    title: 'Natuursteen behandelen',
    path: '/natuursteen-behandelen',
    links: [
      { name: 'Marmer', path: '/natuursteen-behandelen/marmer' },
      { name: 'Hardsteen', path: '/natuursteen-behandelen/hardsteen' },
      { name: 'Travertin', path: '/natuursteen-behandelen/travertin' },
      { name: 'Leisteen', path: '/natuursteen-behandelen/leisteen' },
      { name: 'Graniet', path: '/natuursteen-behandelen/graniet' },
      { name: 'Granito', path: '/natuursteen-behandelen/granito' },
      { name: 'Terrazzo', path: '/natuursteen-behandelen/terrazzo' },
      { name: 'Natuursteen', path: '/natuursteen-behandelen/natuursteen' },
      { name: 'Basalt', path: '/natuursteen-behandelen/basalt' },
    ],
  },
  {
    title: 'Stofferen',
    path: '/stofferen',
    links: [
      { name: 'Trap', path: '/stofferen/trap' },
      { name: 'Vloer', path: '/stofferen/vloer' },
      { name: 'Tapijttegels', path: '/stofferen/tapijttegels' },
      { name: 'Meubels', path: '/stofferen/meubels' },
      { name: 'Deurmat', path: '/stofferen/deurmat' },
      { name: 'Droogloopmat', path: '/stofferen/droogloopmat' },
      { name: 'Rode loper', path: '/stofferen/rode-loper' },
      { name: 'Reinigingsservice', path: '/stofferen/reinigingsservice' },
      { name: 'Tapijt verwijderen', path: '/stofferen/tapijt-verwijderen' },
    ],
  },
  {
    title: 'Overig',
    path: '/overig',
    links: [
      { name: 'Vloerverwarming', path: '/overig/vloerverwarming' },
      { name: 'Egaliseren', path: '/overig/egaliseren' },
      { name: 'Gietvloeren', path: '/overig/gietvloeren' },
      { name: 'Tegelen', path: '/overig/tegelen' },
      { name: 'Vloer verwijderen', path: '/overig/vloer-verwijderen' },
      { name: 'Natuursteen behandelen', path: '/overig/natuursteen-behandelen' },
      { name: 'Opslag', path: '/overig/opslag' },
    ],
  },
  {
    title: 'Mogelijke locaties',
    path: '/mogelijke-locaties',
    links: [
      { name: 'Badkamer', path: '/vloeren-leggen' },
      { name: 'Woonkamer', path: '/vloeren-leggen' },
      { name: 'Horecavloer', path: '/vloeren-leggen' },
      { name: 'Sportvloer', path: '/vloeren-leggen' },
      { name: 'Winkelvloer', path: '/vloeren-leggen' },
      { name: 'Bedrijfsvloer', path: '/vloeren-leggen' },
      { name: 'Bedrijfshal', path: '/vloeren-leggen' },
      { name: 'Muren', path: '/vloeren-leggen' },
    ],
  },
];
