export interface LinkInfo {
  name: string;
  path: string;
}

export interface FooterColumnInfo {
  title: string;
  links: LinkInfo[];
}

export const topFooterLinks: LinkInfo[] = [
  { name: 'Home', path: '/' },
  { name: 'Over ons', path: '/over-ons' },
  { name: 'Diensten', path: '/diensten' },
  { name: 'Zakelijk', path: '/' },
  { name: 'Veelgestelde vragen', path: '/' },
  { name: 'Contact', path: '/' },
];
export const footerColumnsInfo: FooterColumnInfo[] = [
  {
    title: 'Traprenovaties',
    links: [
      { name: 'Bekleden met PVC', path: '' },
      { name: 'Bekleden met laminaat', path: '' },
      { name: 'Bekleden met hout', path: '' },
      { name: 'Bekleden met tapijt', path: '' },
      { name: 'Bekleden met linoleum', path: '' },
      { name: 'Schuren en behandelen', path: '' },
      { name: 'Schuren en schilderen', path: '' },
      { name: 'Hout look', path: '' },
      { name: 'Beton look', path: '' },
      { name: 'Marmer look', path: '' },
      { name: 'Cement look', path: '' },
      { name: 'Staal look', path: '' },
      { name: 'BetonCiré Metal stuc', path: '' },
      { name: 'BetonCiré Glamour stuc', path: '' },
      { name: 'BetonCiré Brut', path: '' },
      { name: 'BetonCiré Parel', path: '' },
      { name: 'BetonCiré Croco', path: '' },
      { name: 'BetonCiré Venetiaans', path: '' },
      { name: 'BetonCiré Acoustic', path: '' },
      { name: '', path: '' },
      { name: 'Open trap', path: '' },
      { name: 'Dichte trap', path: '' },
      { name: 'Verlichting', path: '' },
      { name: 'Tapijt verwijderen', path: '' },
    ],
  },
  {
    title: 'Tegelen',
    links: [
      { name: 'Vloer', path: '' },
      { name: 'Wand', path: '' },
      { name: 'Badkamer', path: '' },
      { name: 'Betonlook', path: '' },
      { name: 'Houtlook', path: '' },
      { name: 'Visgraat', path: '' },
      { name: 'Portugees', path: '' },
      { name: 'Marokkaans', path: '' },
      { name: 'Marmer', path: '' },
      { name: 'Keramisch', path: '' },
      { name: 'Hexagon', path: '' },
    ],
  },
  {
    title: 'Vloeren leggen',
    links: [
      { name: 'Parket leggen', path: '' },
      { name: 'Laminaat leggen', path: '' },
      { name: 'PVC leggen', path: '' },
      { name: 'Tapijt leggen', path: '' },
      { name: 'Linoleum leggen', path: '' },
      { name: 'Visgraat', path: '' },
      { name: 'Walvisgraat', path: '' },
      { name: 'Hongaarse punt', path: '' },
      { name: 'Weense punt', path: '' },
      { name: 'Tegel', path: '' },
      { name: 'Mozaïk of patroon', path: '' },
      { name: 'Hexagon & 3D', path: '' },
      { name: 'Tapis', path: '' },
      { name: 'Bourgogne', path: '' },
    ],
  },
  {
    title: 'Vloer verwijderen',
    links: [
      { name: 'Parket', path: '' },
      { name: 'PVC', path: '' },
      { name: 'Hout', path: '' },
      { name: 'Linoleum', path: '' },
      { name: 'Kurk', path: '' },
      { name: 'Tegels', path: '' },
      { name: 'Marmer', path: '' },
      { name: 'Graniet', path: '' },
      { name: 'Lijmesten', path: '' },
      { name: 'Vinyl', path: '' },
      { name: 'Zandcement dekvloer', path: '' },
    ],
  },
  {
    title: 'Gietvloeren',
    links: [
      { name: 'Epoxy', path: '' },
      { name: 'PU', path: '' },
      { name: 'Woonbeton', path: '' },
      { name: 'Beton', path: '' },
      { name: 'BetonCiré', path: '' },
    ],
  },
  {
    title: 'Parket renovatie',
    links: [
      { name: 'Schuren en polijsten', path: '' },
      { name: 'Schuren en lakken', path: '' },
      { name: 'Schuren en olien', path: '' },
      { name: 'Schuren en hardwaxen', path: '' },
      { name: 'Aanhelen', path: '' },
      { name: 'Reparatie', path: '' },
      { name: 'Drevelen', path: '' },
      { name: 'V-groef frezen', path: '' },
      { name: 'Plinten & Deklijsten', path: '' },
    ],
  },
  {
    title: 'Natuursteen behandelen',
    links: [
      { name: 'Marmer', path: '' },
      { name: 'Hardsteen', path: '' },
      { name: 'Travertin', path: '' },
      { name: 'Leisteen', path: '' },
      { name: 'Graniet', path: '' },
      { name: 'Granito', path: '' },
      { name: 'Terrazzo', path: '' },
      { name: 'Natuursteen', path: '' },
      { name: 'Basalt', path: '' },
    ],
  },
  {
    title: 'Stofferen',
    links: [
      { name: 'Trap', path: '' },
      { name: 'Vloer', path: '' },
      { name: 'Tapijttegels', path: '' },
      { name: 'Meubels', path: '' },
      { name: 'Deurmat', path: '' },
      { name: 'Droogloopmat', path: '' },
      { name: 'Rode loper', path: '' },
      { name: 'Reinigingsservice', path: '' },
    ],
  },
  {
    title: 'Overig',
    links: [
      { name: 'Vloerverwarming', path: '' },
      { name: 'Egaliseren', path: '' },
      { name: 'Gietvloeren', path: '' },
      { name: 'Tegelen', path: '' },
      { name: 'Vloer verwijderen', path: '' },
      { name: 'Natuursteen behandelen', path: '' },
      { name: 'Opslag      ', path: '' },
    ],
  },
  {
    title: 'Mogelijke locaties',
    links: [
      { name: 'Badkamer', path: '' },
      { name: 'Woonkamer', path: '' },
      { name: 'Horecavloer', path: '' },
      { name: 'Sportvloer', path: '' },
      { name: 'Winkelvloer', path: '' },
      { name: 'Bedrijfsvloer', path: '' },
      { name: 'Bedrijfshal', path: '' },
      { name: 'Muren', path: '' },
    ],
  },
];
